site_name: HPCPy
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
theme: 
  name: material

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true